# Generated by Django 3.1.4 on 2021-04-06 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210406_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_date',
        ),
        migrations.AddField(
            model_name='task',
            name='assDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 16, 13, 38, 465471)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 16, 13, 38, 465521)),
        ),
    ]
