# Generated by Django 3.1.4 on 2021-04-08 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20210408_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 10, 51, 51, 614)),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 10, 51, 51, 640)),
        ),
    ]
