# Generated by Django 3.1.4 on 2021-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210413_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
