# Generated by Django 3.1.4 on 2021-04-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_empprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empprofile',
            options={},
        ),
    ]
