# Generated by Django 3.1.4 on 2021-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20210414_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Under Review'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Under Review'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='EmpProfile',
        ),
    ]
