# Generated by Django 3.1.4 on 2021-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20210508_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateField(),
        ),
    ]
