# Generated by Django 2.2.23 on 2021-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20210513_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTime',
        ),
    ]
