# Generated by Django 2.2.23 on 2021-05-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_delete_tasktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uoc',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimatedTime', models.CharField(max_length=100)),
                ('userAddedTime', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
            ],
        ),
    ]
