# Generated by Django 3.1.4 on 2020-12-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_userprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
    ]
