# Generated by Django 3.1.4 on 2021-04-14 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0016_empprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='EmpID', to=settings.AUTH_USER_MODEL),
        ),
    ]
