# Generated by Django 3.1.4 on 2021-04-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0017_empprofile_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.FloatField()),
                ('attend', models.FloatField()),
                ('commu', models.IntegerField()),
                ('attitude', models.IntegerField()),
                ('emp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
