# Generated by Django 3.1.4 on 2021-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_empappraisal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empappraisal',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
