# Generated by Django 3.1.4 on 2021-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_empappraisal_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='empappraisal',
            name='goals',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='attend',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='attitude',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='commu',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='job',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7),
        ),
    ]
