# Generated by Django 3.1.4 on 2021-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20210419_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joining',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=6),
        ),
    ]
