# Generated by Django 3.1.4 on 2021-04-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0021_auto_20210419_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_satisfaction', models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7)),
                ('team_satisfaction', models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7)),
                ('commute_satisfaction', models.CharField(choices=[('0', 'None'), ('1', 'Excellent'), ('2', 'Good'), ('3', 'Bad'), ('4', 'Poor')], default=0, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
