# Generated by Django 3.1.4 on 2021-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_selfeval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfeval',
            name='commute_satisfaction',
        ),
        migrations.RemoveField(
            model_name='selfeval',
            name='manager_satisfaction',
        ),
        migrations.RemoveField(
            model_name='selfeval',
            name='team_satisfaction',
        ),
        migrations.AddField(
            model_name='selfeval',
            name='collaboration',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='communication_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='employee_policies',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='innovation',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='interpersonal_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='leadership_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='productivity',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='professionalism',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='project_management_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='quality_of_work',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='technical_knowledge',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='technical_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='technology_skills',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='selfeval',
            name='time_management',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='attend',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='attitude',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='commu',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='empappraisal',
            name='job',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
    ]
