# Generated by Django 3.1.4 on 2021-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20210506_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='empappraisal',
            name='coworker_relations',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='empappraisal',
            name='creativity',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='empappraisal',
            name='dependibility',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='empappraisal',
            name='group_work',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='empappraisal',
            name='independent_work',
            field=models.CharField(choices=[('0', 'NA'), ('1', 'Inexperienced'), ('2', 'Satisfactory'), ('3', 'Very Competent'), ('4', 'Outstanding')], default=0, max_length=7),
        ),
    ]
