# Generated by Django 3.1.4 on 2021-05-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20210506_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empappraisal',
            name='goals',
        ),
    ]
