# Generated by Django 3.1.4 on 2021-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_remove_empappraisal_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='avg_monthly_hrs',
            field=models.IntegerField(default=210),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='last_evaluation',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='num_projects',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='promotion_last_5_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='satisfaction_level',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='time_spent_company',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='work_accident',
            field=models.IntegerField(default=0),
        ),
    ]
